pull_request:
  azure_pipeline:
    allow_list:
      - "wangzein007-azure-cli"
    result_path: "/test_results/"
  comment:
    group_by_keys:
      - "Module"
      - "Profile"
      - "PythonVersion"
cli_common_issues:
  enable: False
  unofficial_cli:
    keywords:
      - "2.0.80"
      - "2.0.81"
      - "2.18.0"
      - "dist-packages"
      - "2\.\d+\.\d+-\d+"
    solution: 'match unofficial cli'
  not_latest_cli:
    keywords:
      - "2\.\d+\.\d+"
    solution: 'match not latest cli'