pull_request:
  azure_pipeline:
    allow_list:
      - "wangzein007-azure-cli"
    result_path: "/test_results/"
  comment:
    group_by_keys:
      - "Module"
      - "Profile"
      - "PythonVersion"
cli_common_issues:
  enable: True
  unofficial_cli:
    keywords:
      - "2.0.80"
      - "2.0.81"
      - "2.18.0"
      - "dist-packages"
      - "2\\.\\d+\\.\\d+-\\d+"
    solution: >
      This is not the official Azure CLI published by Microsoft (#19640).
      Please follow  https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt to install Microsoft official Azure CLI.
  not_latest_cli:
    keywords:
      - "2\\.\\d+\\.\\d+"
    solution: >
      This is not the latest Azure CLI.
      Please upgrade to the latest Azure CLI version by following https://learn.microsoft.com/en-us/cli/azure/update-azure-cli.